# Generated by Django 5.2.7 on 2025-11-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created_on"]},
        ),
    ]
