# Generated by Django 5.2.7 on 2025-11-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="updated_on",
        ),
    ]
