# Generated by Django 5.2.7 on 2025-11-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
