# Generated by Django 5.2.7 on 2025-11-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="approved",
        ),
    ]
