# Generated by Django 5.2.7 on 2025-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_remove_company_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
