# Generated by Django 5.2.7 on 2025-11-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_company_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
    ]
