# Generated by Django 5.2.7 on 2025-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
