# Generated by Django 5.2.7 on 2025-11-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_company_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="full_description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
