# Generated by Django 5.2.7 on 2025-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_company_full_description_alter_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
