# Generated by Django 5.2.7 on 2025-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_alter_company_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
