# Generated by Django 5.2.7 on 2025-11-11 20:43

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avatar",
                    cloudinary.models.CloudinaryField(
                        default="default_avatar", max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "display_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("bio", models.TextField(blank=True, max_length=1000, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profiles",
                "ordering": ["-updated_on"],
            },
        ),
    ]
