# Generated by Django 5.2.7 on 2025-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
