# Generated by Django 5.2.7 on 2025-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
