# Generated by Django 5.2.7 on 2025-11-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_alter_userprofile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="display_email",
            field=models.EmailField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
