# Generated by Django 5.2.7 on 2025-11-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created_on"]},
        ),
    ]
